//테스트용 파일
const posts = [
  {
    no: 1,
    title: "신선한 사과즙 판매",
    images: [
      "https://loremflickr.com/320/240/apple1",
      "https://loremflickr.com/320/240/apple2",
      "https://loremflickr.com/320/240/apple3",
    ],
    price: "20000",
    likes: 15,
    user: {
      image: "https://randomuser.me/api/portraits/men/32.jpg",
      name: "홍길동",
      grade: "만년설",
    },
    chatCount: 3,
    status: 0,
    type: 1,
    way: 0,
    sdd: "2024-03-23T10:30:00.000Z",
    comment: "신선하고 맛있는 사과즙입니다!",
    liked: true,
  },
  {
    no: 2,
    title: "오가닉 주스 판매",
    images: [
      "https://loremflickr.com/320/240/juice1",
      "https://loremflickr.com/320/240/juice2",
    ],
    price: "25000",
    likes: 20,
    user: {
      image: "https://randomuser.me/api/portraits/women/45.jpg",
      name: "앨리스 존슨",
      grade: "함박눈",
    },
    chatCount: 5,
    status: 2,
    type: 0,
    way: 2,
    sdd: "2024-05-23T15:45:00.000Z",
    comment: "건강한 오가닉 주스를 만나보세요!",
    liked: true,
  },
  {
    no: 3,
    title: "고급 수제 케이크 주문 받습니다",
    images: [
      "https://loremflickr.com/320/240/cake1",
      "https://loremflickr.com/320/240/cake2",
    ],
    price: "45000",
    likes: 35,
    user: {
      image: "https://randomuser.me/api/portraits/men/46.jpg",
      name: "찰리 브라운",
      grade: "첫눈",
    },
    chatCount: 2,
    status: 1,
    type: 1,
    way: 1,
    sdd: "2024-06-15T11:20:00.000Z",
    comment: "생일이나 특별한 날에 맞는 수제 케이크!",
    liked: true,
  },
  {
    no: 4,
    title: "핸드메이드 목걸이 신상 입고",
    images: [
      "https://loremflickr.com/320/240/necklace1",
      "https://loremflickr.com/320/240/necklace2",
    ],
    price: "15000",
    likes: 8,
    user: {
      image: "https://randomuser.me/api/portraits/women/47.jpg",
      name: "에밀리 도",
      grade: "만년설",
    },
    chatCount: 4,
    status: 0,
    type: 0,
    way: 0,
    sdd: "2024-07-03T09:10:00.000Z",
    comment: "세련된 핸드메이드 목걸이, 여기서만!",
    liked: false,
  },
  {
    no: 5,
    title: "자연산 진미채 초특가",
    images: [
      "https://loremflickr.com/320/240/fish1",
      "https://loremflickr.com/320/240/fish2",
    ],
    price: "30000",
    likes: 13,
    user: {
      image: "https://randomuser.me/api/portraits/men/48.jpg",
      name: "정호랑",
      grade: "함박눈",
    },
    chatCount: 3,
    status: 1,
    type: 1,
    way: 1,
    sdd: "2024-08-01T12:30:00.000Z",
    comment: "자연산 진미채, 지금 바로 구매 가능!",
    liked: false,
  },
  {
    no: 6,
    title: "프리미엄 망고 판매",
    images: [
      "https://loremflickr.com/320/240/mango1",
      "https://loremflickr.com/320/240/mango2",
      "https://loremflickr.com/320/240/mango3",
    ],
    price: "6770000",
    likes: 3,
    user: {
      image: "https://randomuser.me/api/portraits/men/49.jpg",
      name: "김민수",
      grade: "만년설",
    },
    chatCount: 1,
    status: 0,
    type: 1,
    way: 0,
    sdd: "2024-09-10T08:30:00.000Z",
    comment: "달콤한 망고 구매하실 분!",
    liked: false,
  },
  {
    no: 7,
    title: "고급 수입 치즈 판매",
    images: [
      "https://loremflickr.com/320/240/cheese1",
      "https://loremflickr.com/320/240/cheese2",
    ],
    price: "4564000",
    likes: 3,
    user: {
      image: "https://randomuser.me/api/portraits/women/50.jpg",
      name: "서윤아",
      grade: "첫눈",
    },
    chatCount: 1,
    way: 2,
    status: 2,
    type: 1,
    sdd: "2024-10-15T14:45:00.000Z",
    comment: "집들이 선물로 딱인 고급 치즈!",
    liked: true,
  },
  {
    no: 8,
    title: "가정용 공기청정기 판매",
    images: [
      "https://loremflickr.com/320/240/airpurifier1",
      "https://loremflickr.com/320/240/airpurifier2",
      "https://loremflickr.com/320/240/airpurifier3",
    ],
    price: "352345000",
    likes: 3,
    user: {
      image: "https://randomuser.me/api/portraits/men/51.jpg",
      name: "조민준",
      grade: "함박눈",
    },
    chatCount: 1,
    status: 1,
    way: 1,
    type: 1,
    sdd: "2024-11-23T17:00:00.000Z",
    comment: "신형 공기청정기, 저렴하게 판매합니다!",
    liked: true,
  },
  {
    no: 9,
    title: "스마트워치 최신 모델",
    images: [
      "https://loremflickr.com/320/240/smartwatch1",
      "https://loremflickr.com/320/240/smartwatch2",
    ],
    price: "20000",
    likes: 3,
    user: {
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      name: "이예림",
      grade: "첫눈",
    },
    chatCount: 1,
    way: 2,
    status: 0,
    sdd: "2024-12-05T12:15:00.000Z",
    comment: "최신 스마트워치, 기능 최고!",
    liked: false,
  },
  {
    no: 10,
    title: "여름용 샌들 신상품 입고",
    images: [
      "https://loremflickr.com/320/240/sandals1",
      "https://loremflickr.com/320/240/sandals2",
    ],
    price: "30500",
    likes: 7,
    user: {
      image: "https://randomuser.me/api/portraits/men/53.jpg",
      name: "박진호",
      grade: "만년설",
    },
    chatCount: 1,
    way: 1,
    type: 0,
    status: 1,
    sdd: "2024-12-25T16:20:00.000Z",
    comment: "신상 샌들, 여름에 딱 맞아요!",
    liked: false,
  },
];

export default posts;
